# Generated by Django 5.0.1

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'api_metrics',
            },
        ),
        migrations.CreateModel(
            name='TrackingNumberRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(db_index=True, max_length=16)),
                ('origin_country_id', models.CharField(max_length=2)),
                ('destination_country_id', models.CharField(max_length=2)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('customer_id', models.UUIDField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_slug', models.CharField(max_length=255)),
                ('request_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(db_index=True, max_length=36)),
            ],
            options={
                'db_table': 'tracking_requests',
            },
        ),
        migrations.AddIndex(
            model_name='apimetrics',
            index=models.Index(fields=['endpoint', 'timestamp'], name='api_metrics_endpoin_b9b7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='apimetrics',
            index=models.Index(fields=['status_code'], name='api_metrics_status__7b8b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingnumberrequest',
            index=models.Index(fields=['tracking_number'], name='tracking_re_trackin_e8b5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingnumberrequest',
            index=models.Index(fields=['correlation_id'], name='tracking_re_correla_a8b9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingnumberrequest',
            index=models.Index(fields=['created_at'], name='tracking_re_created_d4e5f6_idx'),
        ),
    ]
